# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "home"
name = "Home | 主页"
url = "/"
[main.params]
icon = "home"
newtab = true
weight = 1

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/chenzhuowei"
weight = 1

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/floyiac"
weight = 2

[social.params]
icon = "brand-github"
